/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/characters/Zombie.glb -o src/components/Experience/Characters/Zombie.jsx -r public 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Zombie(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/characters/Zombie.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="Armature">
            <primitive object={nodes.mixamorigHips} />
          </group>
          <skinnedMesh
            name="Character"
            geometry={nodes.Character.geometry}
            material={materials.ColorSwatch}
            skeleton={nodes.Character.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/characters/Zombie.glb");
